<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\EquipmentLoan.Application\EquipmentLoan.Application.csproj" />
      <ProjectReference Include="..\EquipmentLoan.Domain\EquipmentLoan.Domain.csproj" />
      <ProjectReference Include="..\EquipmentLoan.Exceptions\EquipmentLoan.Exceptions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Data\" />
      <Folder Include="Migrations\" />
      <Folder Include="Repositories\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
    </ItemGroup>

</Project>
