<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\EquipmentLoan.Domain\EquipmentLoan.Domain.csproj" />
      <ProjectReference Include="..\EquipmentLoan.Exceptions\EquipmentLoan.Exceptions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.IdentityModel.Tokens">
        <HintPath>..\..\..\..\..\..\..\.nuget\packages\microsoft.identitymodel.tokens\7.0.3\lib\net8.0\Microsoft.IdentityModel.Tokens.dll</HintPath>
      </Reference>
      <Reference Include="System.IdentityModel.Tokens.Jwt">
        <HintPath>..\..\..\..\..\..\..\.nuget\packages\system.identitymodel.tokens.jwt\7.0.3\lib\net8.0\System.IdentityModel.Tokens.Jwt.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
